name: armTemplateDeployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  armDeploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-githubactions
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId:  ca911895-5fd7-4efb-9266-551f6802f785
          region: westus2
          template: ./arm-templates/resourcegroup.json
          parameters:
            location=westus2
            resourceGroupName=rg-githubactions
          deploymentName: rg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId:  ca911895-5fd7-4efb-9266-551f6802f785
          template: ./arm-templates/storageaccount.json
          parameters:
            sku=Standard_LRS
            storageAccountName=globostg755
            location=westus2
          deploymentMode: incremental

      - name: Deploy Virtual machine
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          subscriptionId:  ca911895-5fd7-4efb-9266-551f6802f785
          template: ./arm-templates/virtualmachine.json
          parameters:
            adminPassword="My$ecureP@ssword!"
          deploymentMode: incremental
